// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723214308_AddGroupPosterPath")]
    partial class AddGroupPosterPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.MovieSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MovieSpaces");
                });

            modelBuilder.Entity("Backend.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CinemaId")
                        .HasColumnType("integer");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FilmId")
                        .HasColumnType("integer");

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text")
                        .HasColumnName("google_place_id");

                    b.Property<string>("HangoutNotes")
                        .HasColumnType("text")
                        .HasColumnName("hangout_notes");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<string>("PostActivities")
                        .HasColumnType("text")
                        .HasColumnName("post_activities");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_sent");

                    b.Property<DateTime?>("ScreeningTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("screening_time");

                    b.Property<string>("SeasonEpisodeInfo")
                        .HasColumnType("text")
                        .HasColumnName("season_episode_info");

                    b.Property<string>("ShowDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShowTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShowtimeReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("showtime_report_count");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SpaceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("space_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TheaterLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("theater_latitude");

                    b.Property<double?>("TheaterLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("theater_longitude");

                    b.Property<int?>("TmdbMovieId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_movie_id");

                    b.Property<long?>("TotalCostCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cost_cents");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Backend.Models.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Backend.Models.PushToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("PushTokens");
                });

            modelBuilder.Entity("Backend.Models.GroupMember", b =>
                {
                    b.HasOne("Backend.Models.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
