// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823192711_AddAfterActivitiesToGroupMembers")]
    partial class AddAfterActivitiesToGroupMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.MovieSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MovieSpaces");
                });

            modelBuilder.Entity("Backend.Models.CineMindMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CastJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cast_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Director")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("director");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genres_json");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<bool>("SurpriseMe")
                        .HasColumnType("boolean")
                        .HasColumnName("surprise_me");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .IsUnique();

                    b.ToTable("cinemind_movies");
                });

            modelBuilder.Entity("Backend.Models.CineMindReminderLog", b =>
                {
                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_count");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("PuzzleDate");

                    b.ToTable("cinemind_reminder_log");
                });

            modelBuilder.Entity("Backend.Models.CineMindTvShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CastJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cast_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genres_json");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("cinemind_tv_shows");
                });

            modelBuilder.Entity("Backend.Models.DailyPuzzle", b =>
                {
                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.Property<string>("ChallengePayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("challenge_payload_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PuzzleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("puzzle_number");

                    b.HasKey("PuzzleDate");

                    b.ToTable("daily_puzzles");
                });

            modelBuilder.Entity("Backend.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("CinemaId")
                        .HasColumnType("integer");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventCategory")
                        .HasColumnType("text")
                        .HasColumnName("event_category");

                    b.Property<int?>("FilmId")
                        .HasColumnType("integer");

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenreCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("genre_category");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("google_place_id");

                    b.Property<string>("HangoutNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hangout_notes");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("MatchMovieKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("match_movie_key");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<string>("PostActivities")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("post_activities");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("poster_path");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_sent");

                    b.Property<DateTime?>("ScreeningTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("screening_time");

                    b.Property<string>("SeasonEpisodeInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("season_episode_info");

                    b.Property<string>("ShowDate")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ShowTime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ShowtimeReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("showtime_report_count");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<string>("SpaceCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("space_code");

                    b.Property<string>("SpaceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("space_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TheaterLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("theater_latitude");

                    b.Property<double?>("TheaterLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("theater_longitude");

                    b.Property<int?>("TmdbMovieId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_movie_id");

                    b.Property<long?>("TotalCostCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cost_cents");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SpaceCode")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Backend.Models.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterActivities")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuestToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasTicket")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Backend.Models.PushToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("PushTokens");
                });

            modelBuilder.Entity("Backend.Models.PuzzleFirstSeen", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_utc");

                    b.HasKey("UserId", "PuzzleDate");

                    b.ToTable("PuzzleFirstSeen");
                });

            modelBuilder.Entity("Backend.Models.RouletteSpinHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("challenge_type");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imdb_id");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SeenAt");

                    b.ToTable("roulette_spin_history");
                });

            modelBuilder.Entity("Backend.Models.ScrapedShowtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MovieSlug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("movie_slug");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("movie_title");

                    b.Property<DateTime>("ScrapedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at_utc");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("date")
                        .HasColumnName("show_date");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("start_minutes");

                    b.Property<string>("TheaterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("theater_name");

                    b.Property<string>("TheaterSlug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("theater_slug");

                    b.HasKey("Id");

                    b.HasIndex("TheaterSlug", "ShowDate");

                    b.ToTable("ScrapedShowtimes");
                });

            modelBuilder.Entity("Backend.Models.UserDailyProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChallengesSolvedCount")
                        .HasColumnType("integer")
                        .HasColumnName("challenges_solved_count");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("GuessHistoryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guess_history_json");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer")
                        .HasColumnName("streak_count");

                    b.Property<int>("TimeTakenMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_taken_ms");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleDate");

                    b.HasIndex("UserId", "PuzzleDate")
                        .IsUnique();

                    b.ToTable("user_daily_progress");
                });

            modelBuilder.Entity("Backend.Models.GroupMember", b =>
                {
                    b.HasOne("Backend.Models.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
